/*
 * config.h
 *
 *  Created on: Jan 20, 2016
 *      Author: Jonathan
 */

#ifndef SRC_CONFIG_H_
#define SRC_CONFIG_H_

//Shooter Speeds 1 = 100% 0 = 0% etc
#define SHOOTER_IDLE_SPEED 0
#define SHOOTER_SHOOT_SPEED 0.2
#define SHOOTER_UNLOAD_SPEED 0.1
#define SHOOTER_RETRACT_SPEED -0.15

//Shooter Timing... this is in seconds!!
#define SHOOTER_SHOOT_CANCELLATION_TIME_MS .7
#define SHOOTER_PLATFORM_CANCELLATION_TIME_MS .5

//Motor Channels PWM
#define LEFT_ARMS_MOTOR_CHANNEL 0
#define RIGHT_ARMS_MOTOR_CHANNEL 1
#define SHOOTER_RIGHT_LAUNCH_MOTOR_CHANNEL 2
#define SHOOTER_LEFT_LAUNCH_MOTOR_CHANNEL 3
#define DRIVE_MOTOR_RIGHT_REAR_CHANNEL 4
#define DRIVE_MOTOR_RIGHT_FRONT_CHANNEL 5
#define DRIVE_MOTOR_LEFT_REAR_CHANNEL 6
#define DRIVE_MOTOR_LEFT_FRONT_CHANNEL 7
#define BALLY_LAUNCHY_THINGY_5064_EXTREME_XD_1337_CHANNEL 8

//Sensor Channels Digital I/O
#define SHOOTER_BALL_LOADED_SENSOR_CHANNEL 0
#define ARMS_ENCODER_CHANNEL_A 1
#define ARMS_ENCODER_CHANNEL_B 2
#define ARMS_ENCODER_INDEX_CHANNEL 3


//Joystick
	//Shooter buttons


	//Arms buttons




#endif /* SRC_CONFIG_H_ */
